version: '3'
services:
  gateway:
    build: .
    network_mode: host
    restart: always
    volumes:
      - ./config/config.yaml:./config/config.yaml
    deploy:
      resources:
        limits:
          cpus: '8.00'
          memory: '8192M'
