version: '3.5'
services:
  gateway:
    environment:
      - APP_NAME=Manager
      - CONF_HOST=${CONF_HOST}
      - CONF_TOKEN=${CONF_TOKEN}
    image: limescloud/gateway
    container_name: gateway
    network_mode: host
    restart: always
    volumes:
      - ./tmp:/go/build/tmp