
debug: true
addr: 0.0.0.0:7080
name: gateway
version: v1
middlewares:
  - name: bbr
  - name: cors
    options:
      allowCredentials: true
      allowOrigins:
        - '*'
      allowMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      AllowHeaders:
        - Content-Type
        - Content-Length
        - Authorization
      ExposeHeaders:
        - Content-Length
        - Access-Control-Allow-Headers
  - name: tracing
  - name: logging
  - name: transcoder
endpoints:
  - path: /manager/api/v1/*
    timeout: 10s
    protocol: HTTP
    responseFormat: true
    backends:
      - target: 127.0.0.1:7001
  - path: /resource/api/v1/*
    timeout: 60s
    protocol: HTTP
    responseFormat: true
    backends:
      - target: 127.0.0.1:7003
    middlewares:
      - name: auth
        options:
          url: http://localhost:7080/manager/api/v1/auth
          method: POST
          whiteList:
            - path: /resource/api/v1/static/*
              method: GET
  - path: /resource/client/*
    timeout: 60s
    protocol: HTTP
    responseFormat: true
    backends:
      - target: 127.0.0.1:7003
    middlewares:
      - name: auth
        options:
          url: http://localhost:7080/usercenter/client/v1/auth
          method: POST
  - path: /usercenter/api/v1/*
    timeout: 60s
    protocol: HTTP
    responseFormat: true
    backends:
      - target: 127.0.0.1:7004
    middlewares:
      - name: auth
        options:
          url: http://localhost:7080/manager/api/v1/auth
          method: POST
  - path: /usercenter/client/v1/*
    timeout: 60s
    protocol: HTTP
    responseFormat: true
    backends:
      - target: 127.0.0.1:7004
  - path: /configure/api/v1/*
    timeout: 60s
    protocol: HTTP
    responseFormat: true
    backends:
      - target: 127.0.0.1:6081