debug: true
addr: 0.0.0.0:8080
name: gateway
version: v1

middlewares:
  - name: cors
  - name: tracing
  - name: logging
  - name: transcoder
    options:
      allowCredentials: true
      allowOrigins: ["*"]
      allowMethods: ["GET","POST","PUT","DELETE","OPTIONS"]
endpoints:
  - path: /*
    timeout: 60s
    protocol: HTTP
    host: localhost
    responseFormat: true
    backends:
      - target: '127.0.0.1:8001'
    middlewares:
      - name: circuitbreaker
        options:
          trigger:
            successRatio: {"success":0.6, "request":1, "bucket":10, "window":3s}
      - name: rewrite
        options:
          stripPrefix: /basic

