debug: true
addr: 0.0.0.0:7080
name: gateway
version: v1
middlewares:
  - name: cors
    options:
      allowCredentials: true
      allowOrigins: [ "*" ]
      allowMethods: [ "GET","POST","PUT","DELETE","OPTIONS" ]
      AllowHeaders: ["Content-Type", "Content-Length", "Authorization"]
      ExposeHeaders: ["Content-Length", "Access-Control-Allow-Headers"]
  - name: tracing
  - name: logging
  - name: transcoder
endpoints:
  - path: /basic/*
    timeout: 10s
    protocol: HTTP
    host: localhost
    responseFormat: true
    backends:
      - target: '127.0.0.1:7002'
  - path: /configure/*
    timeout: 10s
    protocol: HTTP
    host: localhost
    responseFormat: true
    backends:
      - target: '127.0.0.1:7003'

